### ISSUE TITLE
"Tags" properties have incorrect OData type

### ISSUE THREAD

**Issue by fmmich** [jsreport/jsreport-tags#1]
If a template has more than one tag, I receive an error from our OData Client attempting to retrieve the list of templates (using http://localhost:5488/odata/templates).  I traced this to an incorrect declaration of the "tags" property in the metadata (using http://localhost:5488/odata/$metadata#templates).

It appears that all "tags" properties are declared as "Collection(Edm.String)" when they should actually be declared as a collection of a dedicated ComplexType with a single property "shortid," similar to how the "xlsxTemplate" property is declared.

To replicate the problem, place two tags on a report, then use an OData Client (I'm using Simple.OData.Client for .NET) to retrieve the list of templates.  In Visual Studio 2015 using C#:

`var jsreportMetadata = new ODataClient('http://localhost:5488/odata");`
`var templates = await jsreportMetadata.For<Template>().FindEntriesAsync();`

I expect an IEnumerable<Template>, but I get a JSON parsing exception instead.  The exception doesn't occur if all of templates have zero or one tag.

For the short term, we are limiting our reports to one tag.  Thank you for your consideration.

**Comment by bjrmatos** [comment]
thnks for the reporting this, i'm working on the issue.

**Comment by bjrmatos** [comment]
fixed in `v1.0.3`, @fmmich can you try it? if you are using normal jsreport installation (node.js) then you just need to `npm install jsreport-tags@1.0.3 --save` in order to have the latest version of tags in your jsreport installation.

this fix will be integrated in the next version of `jsreport`

**Comment by fmmich** [comment]
Success!  I am no longer getting a JSON parsing exception retrieving templates with tags via OData.  You may close this issue.
